const zcAgentSectionPattern = /^\[agents\.(zc_[A-Za-z0-9_]+)\]\s*$/;
const tomlSectionPattern = /^\[{1,2}[^\r\n]+\]{1,2}(?:\s+#.*)?$/u;
const zcGeneratedCommentLines = new Set([
  "# Generated by zc. Merge with existing Codex config before forcing overwrites.",
  "# See: https://developers.openai.com/codex/config-reference",
]);

export function listZcAgentConfigNames(content: string): readonly string[] {
  return content
    .split(/\r?\n/)
    .map((line) => line.trim().match(zcAgentSectionPattern)?.[1] ?? null)
    .filter((name): name is string => name !== null);
}

export function stripManagedZcAgentSections(
  content: string,
  managedAgentNames?: readonly string[],
): string {
  const lines = content.split(/\r?\n/);
  const kept: string[] = [];
  const managedNames = managedAgentNames === undefined
    ? null
    : new Set(managedAgentNames);
  let skipping = false;

  for (const line of lines) {
    const trimmed = line.trim();

    if (zcGeneratedCommentLines.has(trimmed)) {
      continue;
    }

    const agentSection = trimmed.match(zcAgentSectionPattern);
    if (
      agentSection
      && (managedNames === null || managedNames.has(agentSection[1]!))
    ) {
      skipping = true;
      continue;
    }

    if (skipping && tomlSectionPattern.test(trimmed)) {
      skipping = false;
    }

    if (!skipping) {
      kept.push(line);
    }
  }

  return kept.join("\n").trimEnd();
}

export function isCodexAgentConfigContent(content: string): boolean {
  return content.split(/\r?\n/).some((line) => zcAgentSectionPattern.test(line.trim()));
}

export function mergeCodexAgentConfig(existingContent: string | undefined, generatedContent: string): string {
  if (!existingContent?.trim()) {
    return `${generatedContent.trimEnd()}\n`;
  }

  const baseContent = stripManagedZcAgentSections(existingContent);
  const generatedBlock = generatedContent.trimEnd();

  if (!baseContent.trim()) {
    return `${generatedBlock}\n`;
  }

  return `${baseContent}\n\n${generatedBlock}\n`;
}

export function mergeOwnedCodexAgentConfig(
  existingContent: string | undefined,
  generatedContent: string,
  previouslyManagedAgentNames: readonly string[],
): string {
  if (!existingContent?.trim()) {
    return `${generatedContent.trimEnd()}\n`;
  }

  const namesToReplace = [
    ...previouslyManagedAgentNames,
    ...listZcAgentConfigNames(generatedContent),
  ];
  const baseContent = stripManagedZcAgentSections(existingContent, namesToReplace);
  const generatedBlock = generatedContent.trimEnd();

  if (!generatedBlock) {
    return baseContent.trim() ? `${baseContent}\n` : "";
  }

  if (!baseContent.trim()) {
    return `${generatedBlock}\n`;
  }

  return `${baseContent}\n\n${generatedBlock}\n`;
}
