const zcAgentSectionPattern = /^\[agents\.zc_[A-Za-z0-9_]+\]\s*$/;
const tomlSectionPattern = /^\[[^\]]+\]\s*$/;
const zcGeneratedCommentLines = new Set([
  "# Generated by zc. Merge with existing Codex config before forcing overwrites.",
  "# See: https://developers.openai.com/codex/config-reference",
]);

function stripManagedZcAgentSections(content: string): string {
  const lines = content.split(/\r?\n/);
  const kept: string[] = [];
  let skipping = false;

  for (const line of lines) {
    const trimmed = line.trim();

    if (zcGeneratedCommentLines.has(trimmed)) {
      continue;
    }

    if (zcAgentSectionPattern.test(trimmed)) {
      skipping = true;
      continue;
    }

    if (skipping && tomlSectionPattern.test(trimmed)) {
      skipping = false;
    }

    if (!skipping) {
      kept.push(line);
    }
  }

  return kept.join("\n").trimEnd();
}

export function isCodexAgentConfigContent(content: string): boolean {
  return content.split(/\r?\n/).some((line) => zcAgentSectionPattern.test(line.trim()));
}

export function mergeCodexAgentConfig(existingContent: string | undefined, generatedContent: string): string {
  if (!existingContent?.trim()) {
    return `${generatedContent.trimEnd()}\n`;
  }

  const baseContent = stripManagedZcAgentSections(existingContent);
  const generatedBlock = generatedContent.trimEnd();

  if (!baseContent.trim()) {
    return `${generatedBlock}\n`;
  }

  return `${baseContent}\n\n${generatedBlock}\n`;
}
