import assert from "node:assert/strict";
import { describe, it } from "vitest";

import {
  isCodexAgentConfigContent,
  mergeOwnedCodexAgentConfigWithDefaults,
  mergeOwnedCodexAgentConfig,
  mergeCodexAgentConfig,
  stripManagedZcAgentSections,
} from "./codex-config-merge.js";

describe("codex config merge", () => {
  it("detects zc agent config content", () => {
    assert.equal(isCodexAgentConfigContent("[agents.zc_code_reviewer]\nconfig_file = \"agents/zc-code-reviewer.toml\"\n"), true);
    assert.equal(isCodexAgentConfigContent("[agents.other]\nconfig_file = \"agents/other.toml\"\n"), false);
  });

  it("preserves user config while appending generated zc agent sections", () => {
    const existing = [
      'model = "gpt-5.5"',
      "",
      "[plugins.\"github@openai-curated\"]",
      "enabled = true",
      "",
      "[projects.'e:\\workspace\\apps\\ai-coding']",
      'trust_level = "trusted"',
      "",
    ].join("\n");
    const generated = [
      "# Generated by zc. Merge with existing Codex config before forcing overwrites.",
      "",
      "[agents.zc_code_reviewer]",
      'description = "review"',
      'config_file = "agents/zc-code-reviewer.toml"',
      "",
    ].join("\n");

    const merged = mergeCodexAgentConfig(existing, generated);

    assert.match(merged, /model = "gpt-5\.5"/);
    assert.match(merged, /\[plugins\."github@openai-curated"\]/);
    assert.match(merged, /\[projects\.'e:\\workspace\\apps\\ai-coding'\]/);
    assert.match(merged, /\[agents\.zc_code_reviewer\]/);
  });

  it("replaces previous zc agent sections without removing unrelated sections", () => {
    const existing = [
      'model = "gpt-5.5"',
      "",
      "# Generated by zc. Merge with existing Codex config before forcing overwrites.",
      "# See: https://developers.openai.com/codex/config-reference",
      "",
      "[agents.zc_code_reviewer]",
      'description = "old"',
      'config_file = "agents/old.toml"',
      "",
      "[agents.custom]",
      'description = "custom"',
      'config_file = "agents/custom.toml"',
      "",
    ].join("\n");
    const generated = [
      "[agents.zc_code_reviewer]",
      'description = "new"',
      'config_file = "agents/zc-code-reviewer.toml"',
      "",
    ].join("\n");

    const merged = mergeCodexAgentConfig(existing, generated);
    const mergedAgain = mergeCodexAgentConfig(merged, generated);

    assert.doesNotMatch(merged, /description = "old"/);
    assert.match(merged, /\[agents\.custom\]/);
    assert.match(merged, /description = "new"/);
    assert.equal(mergedAgain, merged);
  });

  it("replaces only receipt-owned and newly generated zc agent sections", () => {
    const existing = [
      "[agents.zc_code_reviewer]",
      'description = "old owned"',
      "",
      "[agents.zc_removed_role]",
      'description = "stale owned"',
      "",
      "[agents.zc_local_role]",
      'description = "local"',
      "",
    ].join("\n");
    const generated = [
      "[agents.zc_code_reviewer]",
      'description = "new owned"',
      "",
    ].join("\n");

    const merged = mergeOwnedCodexAgentConfig(
      existing,
      generated,
      ["zc_code_reviewer", "zc_removed_role"],
    );

    assert.doesNotMatch(merged, /old owned|stale owned/);
    assert.match(merged, /\[agents\.zc_local_role\]\n(?:description = "local")/);
    assert.match(merged, /description = "new owned"/);
  });

  it("preserves TOML array tables after a managed zc agent section", () => {
    const existing = [
      "[agents.zc_code_reviewer]",
      'config_file = "agents/zc-code-reviewer.toml"',
      "",
      "[[mcp_servers]]",
      'name = "keep-me"',
      "",
    ].join("\n");

    const merged = mergeOwnedCodexAgentConfig(existing, "", ["zc_code_reviewer"]);

    assert.equal(merged, '[[mcp_servers]]\nname = "keep-me"\n');
  });

  it("keeps user subagent defaults and avoids a duplicate agents table", () => {
    const existing = [
      "[agents] # user defaults",
      "default_subagent_model = 'gpt-user'",
      'default_subagent_reasoning_effort = "high"',
      "",
    ].join("\n");
    const generated = [
      "[agents]",
      'default_subagent_model = "gpt-5.6-terra"',
      'default_subagent_reasoning_effort = "medium"',
      "",
      "[agents.zc_code_reviewer]",
      'config_file = "agents/zc-code-reviewer.toml"',
      "",
    ].join("\n");

    const result = mergeOwnedCodexAgentConfigWithDefaults(existing, generated, [], []);

    assert.equal((result.content.match(/^\[agents\](?:\s*#.*)?$/gmu) ?? []).length, 1);
    assert.match(result.content, /default_subagent_model = 'gpt-user'/);
    assert.match(result.content, /default_subagent_reasoning_effort = "high"/);
    assert.deepEqual(result.managedDefaults, []);
    assert.equal(
      mergeOwnedCodexAgentConfig(result.content, generated, [], result.managedDefaults),
      result.content,
    );
    assert.match(result.content, /default_subagent_reasoning_effort = "high"\n\n\[agents\.zc_code_reviewer\]/);
  });

  it("owns only injected defaults and leaves user-modified owned defaults during removal", () => {
    const generated = [
      "[agents]",
      'default_subagent_model = "gpt-5.6-terra"',
      'default_subagent_reasoning_effort = "medium"',
      "",
    ].join("\n");
    const first = mergeOwnedCodexAgentConfigWithDefaults(undefined, generated, [], []);
    const changedByUser = first.content.replace('default_subagent_model = "gpt-5.6-terra"', 'default_subagent_model = "gpt-user"');

    assert.deepEqual(first.managedDefaults, [
      { key: "default_subagent_model", value: "gpt-5.6-terra" },
      { key: "default_subagent_reasoning_effort", value: "medium" },
    ]);
    assert.equal(
      stripManagedZcAgentSections(changedByUser, [], first.managedDefaults),
      [
        "[agents]",
        'default_subagent_model = "gpt-user"',
      ].join("\n"),
    );
  });

  it("ends managed-agent stripping before a following agents defaults table", () => {
    const content = [
      "[agents.zc_old]",
      'config_file = "agents/zc-old.toml"',
      "",
      "[agents] # user defaults",
      "default_subagent_model = 'gpt-user'",
      "",
    ].join("\n");

    assert.equal(
      stripManagedZcAgentSections(content, ["zc_old"]),
      [
        "[agents] # user defaults",
        "default_subagent_model = 'gpt-user'",
      ].join("\n"),
    );
  });

  it("rejects inline agents instead of silently creating a conflicting table", () => {
    assert.throws(
      () => mergeOwnedCodexAgentConfigWithDefaults(
        'agents = { default_subagent_model = "gpt-user" }\n',
        '[agents]\ndefault_subagent_model = "gpt-5.6-terra"\n',
        [],
        [],
      ),
      /无法安全合并 inline 或 quoted \[agents\] 默认配置/,
    );
  });

  it("merges into a whitespace-normalized agents table", () => {
    const result = mergeOwnedCodexAgentConfigWithDefaults(
      '[ agents ]\ndefault_subagent_model = "gpt-user"\n',
      '[agents]\ndefault_subagent_model = "gpt-5.6-terra"\ndefault_subagent_reasoning_effort = "medium"\n',
      [],
      [],
    );

    assert.equal((result.content.match(/^\[\s*agents\s*\]$/gmu) ?? []).length, 1);
    assert.match(result.content, /default_subagent_model = "gpt-user"/);
    assert.match(result.content, /default_subagent_reasoning_effort = "medium"/);
  });

  it("rejects dotted default assignments that conflict with an agents table", () => {
    assert.throws(
      () => mergeOwnedCodexAgentConfigWithDefaults(
        'agents.default_subagent_model = "gpt-user"\n',
        '[agents]\ndefault_subagent_model = "gpt-5.6-terra"\n',
        [],
        [],
      ),
      /无法安全合并 inline 或 quoted \[agents\] 默认配置/,
    );
  });

  it("rejects quoted dotted and inline agents definitions without appending a table", () => {
    for (const existing of [
      'agents."default_subagent_model" = "gpt-user"\n',
      '"agents".default_subagent_model = "gpt-user"\n',
      "'agents'.'default_subagent_model' = 'gpt-user'\n",
      '"agents" = { default_subagent_model = "gpt-user" }\n',
      'agents.max_concurrent_threads_per_session = 3\n',
    ]) {
      assert.throws(
        () => mergeOwnedCodexAgentConfigWithDefaults(
          existing,
          '[agents]\ndefault_subagent_model = "gpt-5.6-terra"\n',
          [],
          [],
        ),
        /无法安全合并/,
      );
    }
  });

  it("rejects agents array tables that cannot carry global defaults", () => {
    assert.throws(
      () => mergeOwnedCodexAgentConfigWithDefaults(
        '[[agents]]\nname = "custom"\n',
        '[agents]\ndefault_subagent_model = "gpt-5.6-terra"\n',
        [],
        [],
      ),
      /无法安全合并 inline 或 quoted \[agents\] 默认配置/,
    );
  });
});
