import assert from "node:assert/strict";
import { describe, it } from "vitest";

import {
  isCodexAgentConfigContent,
  mergeCodexAgentConfig,
} from "./codex-config-merge.js";

describe("codex config merge", () => {
  it("detects zc agent config content", () => {
    assert.equal(isCodexAgentConfigContent("[agents.zc_code_reviewer]\nconfig_file = \"agents/zc-code-reviewer.toml\"\n"), true);
    assert.equal(isCodexAgentConfigContent("[agents.other]\nconfig_file = \"agents/other.toml\"\n"), false);
  });

  it("preserves user config while appending generated zc agent sections", () => {
    const existing = [
      'model = "gpt-5.5"',
      "",
      "[plugins.\"github@openai-curated\"]",
      "enabled = true",
      "",
      "[projects.'e:\\workspace\\apps\\ai-coding']",
      'trust_level = "trusted"',
      "",
    ].join("\n");
    const generated = [
      "# Generated by zc. Merge with existing Codex config before forcing overwrites.",
      "",
      "[agents.zc_code_reviewer]",
      'description = "review"',
      'config_file = "agents/zc-code-reviewer.toml"',
      "",
    ].join("\n");

    const merged = mergeCodexAgentConfig(existing, generated);

    assert.match(merged, /model = "gpt-5\.5"/);
    assert.match(merged, /\[plugins\."github@openai-curated"\]/);
    assert.match(merged, /\[projects\.'e:\\workspace\\apps\\ai-coding'\]/);
    assert.match(merged, /\[agents\.zc_code_reviewer\]/);
  });

  it("replaces previous zc agent sections without removing unrelated sections", () => {
    const existing = [
      'model = "gpt-5.5"',
      "",
      "# Generated by zc. Merge with existing Codex config before forcing overwrites.",
      "# See: https://developers.openai.com/codex/config-reference",
      "",
      "[agents.zc_code_reviewer]",
      'description = "old"',
      'config_file = "agents/old.toml"',
      "",
      "[agents.custom]",
      'description = "custom"',
      'config_file = "agents/custom.toml"',
      "",
    ].join("\n");
    const generated = [
      "[agents.zc_code_reviewer]",
      'description = "new"',
      'config_file = "agents/zc-code-reviewer.toml"',
      "",
    ].join("\n");

    const merged = mergeCodexAgentConfig(existing, generated);
    const mergedAgain = mergeCodexAgentConfig(merged, generated);

    assert.doesNotMatch(merged, /description = "old"/);
    assert.match(merged, /\[agents\.custom\]/);
    assert.match(merged, /description = "new"/);
    assert.equal(mergedAgain, merged);
  });
});
