import { readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";

import {
  getCodexAgentsReceiptOwnedPaths,
  readCodexAgentsReceipt,
  resolveCodexAgentsReceiptPath,
  type CodexAgentsReceipt,
  type CodexAgentsReceiptScope,
} from "../platform-state/codex-agents-receipt.js";
import {
  isCodexAgentConfigContent,
  stripManagedZcAgentSections,
} from "./codex-config-merge.js";

export interface ReceiptManagedCodexAgents {
  readonly root: string;
  readonly scope: CodexAgentsReceiptScope;
  readonly configPath: string;
  readonly receiptPath: string;
  readonly receipt: CodexAgentsReceipt | null;
  readonly ownedPaths: readonly string[];
}

export function resolveCodexAgentsRootFromMarketplace(
  marketplaceRoot: string,
  scope: CodexAgentsReceiptScope,
): string {
  return scope === "global"
    ? resolve(marketplaceRoot, ".codex")
    : resolve(marketplaceRoot);
}

export async function inspectReceiptManagedCodexAgents(
  marketplaceRoot: string,
  scope: CodexAgentsReceiptScope,
): Promise<ReceiptManagedCodexAgents> {
  const root = resolveCodexAgentsRootFromMarketplace(marketplaceRoot, scope);
  const receiptPath = resolveCodexAgentsReceiptPath(root, scope);
  const receipt = await readCodexAgentsReceipt(receiptPath, {
    root,
    scope,
  });

  return {
    root,
    scope,
    configPath: scope === "project"
      ? join(root, ".codex", "config.toml")
      : join(root, "config.toml"),
    receiptPath,
    receipt,
    ownedPaths: receipt ? getCodexAgentsReceiptOwnedPaths(receipt) : [],
  };
}

export async function stripCodexAgentConfigFile(
  path: string,
  dryRun: boolean,
  managedAgentNames?: readonly string[],
): Promise<{
  readonly changed: boolean;
  readonly missing: boolean;
}> {
  let existing: string;

  try {
    existing = await readFile(path, "utf8");
  } catch (error) {
    if (
      typeof error === "object"
      && error !== null
      && "code" in error
      && error.code === "ENOENT"
    ) {
      return {
        changed: false,
        missing: true,
      };
    }

    throw error;
  }

  if (managedAgentNames !== undefined && managedAgentNames.length === 0) {
    return {
      changed: false,
      missing: false,
    };
  }

  const hasManagedContent =
    isCodexAgentConfigContent(existing)
    || existing.includes("# Generated by zc. Merge with existing Codex config before forcing overwrites.")
    || existing.includes("# See: https://developers.openai.com/codex/config-reference");

  if (!hasManagedContent) {
    return {
      changed: false,
      missing: false,
    };
  }

  const stripped = stripManagedZcAgentSections(existing, managedAgentNames);
  const nextContent = stripped.trim().length > 0 ? `${stripped}\n` : "";
  const changed = existing !== nextContent;

  if (!dryRun && changed) {
    await writeFile(path, nextContent, "utf8");
  }

  return {
    changed,
    missing: false,
  };
}
