const zcAgentSectionPattern = /^\[agents\.(zc_[A-Za-z0-9_]+)\]\s*$/;
const tomlSectionPattern = /^\[{1,2}[^\r\n]+\]{1,2}(?:\s+#.*)?$/u;
const zcGeneratedCommentLines = new Set([
  "# Generated by zc. Merge with existing Codex config before forcing overwrites.",
  "# See: https://developers.openai.com/codex/config-reference",
]);
const codexAgentsSectionPattern = /^\[\s*agents\s*\]\s*(?:#.*)?$/;
const codexAgentDefaultKeys = [
  "default_subagent_model",
  "default_subagent_reasoning_effort",
] as const;
const codexAgentDefaultPattern = /^(\s*)(default_subagent_model|default_subagent_reasoning_effort)\s*=\s*(['"])(.*?)\3\s*(?:#.*)?$/;
const inlineAgentsPattern = /^\s*(?:agents|"agents"|'agents')\s*=/m;
const dottedAgentDefaultPattern = /^\s*(?:agents|"agents"|'agents')\s*\./m;
const agentsArrayTablePattern = /^\s*\[\[\s*agents\s*\]\]\s*(?:#.*)?$/m;
const quotedAgentsSectionPattern = /^\s*\[\s*["']agents["']\s*\]\s*(?:#.*)?$/m;
const quotedAgentDefaultKeyPattern = /^\s*["']default_subagent_(?:model|reasoning_effort)["']\s*=/m;

export type CodexAgentDefaultKey = typeof codexAgentDefaultKeys[number];

export interface ManagedCodexAgentDefault {
  readonly key: CodexAgentDefaultKey;
  readonly value: string;
}

export interface CodexAgentConfigMergeResult {
  readonly content: string;
  readonly managedDefaults: readonly ManagedCodexAgentDefault[];
}

function isTomlSection(line: string): boolean {
  return tomlSectionPattern.test(line.trim());
}

function isCodexAgentsSection(line: string): boolean {
  return codexAgentsSectionPattern.test(line.trim());
}

function readCodexAgentDefaults(content: string): ReadonlyMap<CodexAgentDefaultKey, string> {
  const defaults = new Map<CodexAgentDefaultKey, string>();
  let inAgentsSection = false;

  for (const line of content.split(/\r?\n/)) {
    if (isCodexAgentsSection(line)) {
      inAgentsSection = true;
      continue;
    }
    if (inAgentsSection && isTomlSection(line)) {
      inAgentsSection = false;
    }
    if (!inAgentsSection) {
      continue;
    }
    const match = line.match(codexAgentDefaultPattern);
    if (match) {
      defaults.set(match[2] as CodexAgentDefaultKey, match[4]!);
    }
  }

  return defaults;
}

function stripGeneratedCodexAgentDefaults(content: string): string {
  const lines = content ? content.split(/\r?\n/) : [];
  const result: string[] = [];
  let inAgentsSection = false;
  let agentsSectionStart = -1;

  for (const line of lines) {
    if (isCodexAgentsSection(line)) {
      inAgentsSection = true;
      agentsSectionStart = result.length;
      result.push(line);
      continue;
    }
    if (inAgentsSection && isTomlSection(line)) {
      if (agentsSectionStart >= 0 && result.slice(agentsSectionStart + 1).every((entry) => entry.trim() === "")) {
        result.splice(agentsSectionStart);
      }
      inAgentsSection = false;
      agentsSectionStart = -1;
    }
    if (inAgentsSection && codexAgentDefaultPattern.test(line)) {
      continue;
    }
    result.push(line);
  }

  if (inAgentsSection && agentsSectionStart >= 0 && result.slice(agentsSectionStart + 1).every((entry) => entry.trim() === "")) {
    result.splice(agentsSectionStart);
  }
  return result.join("\n").trimEnd();
}

function mergeCodexAgentDefaults(
  content: string,
  defaultsToWrite: ReadonlyMap<CodexAgentDefaultKey, string>,
): string {
  if (defaultsToWrite.size === 0) {
    return content.trimEnd();
  }

  const lines = content ? content.split(/\r?\n/) : [];
  const result: string[] = [];
  const pending = new Map(defaultsToWrite);
  let inAgentsSection = false;
  let foundAgentsSection = false;

  for (const line of lines) {
    if (isCodexAgentsSection(line)) {
      inAgentsSection = true;
      foundAgentsSection = true;
      result.push(line);
      continue;
    }
    if (inAgentsSection && isTomlSection(line)) {
      for (const [key, value] of pending) {
        result.push(`${key} = ${JSON.stringify(value)}`);
      }
      pending.clear();
      inAgentsSection = false;
    }
    if (inAgentsSection) {
      const match = line.match(codexAgentDefaultPattern);
      if (match && pending.has(match[2] as CodexAgentDefaultKey)) {
        const key = match[2] as CodexAgentDefaultKey;
        result.push(`${match[1]}${key} = ${JSON.stringify(pending.get(key)!)}`);
        pending.delete(key);
        continue;
      }
    }
    result.push(line);
  }

  if (inAgentsSection) {
    for (const [key, value] of pending) {
      result.push(`${key} = ${JSON.stringify(value)}`);
    }
    pending.clear();
  }
  if (!foundAgentsSection) {
    if (result.length > 0 && result[result.length - 1]!.trim() !== "") {
      result.push("");
    }
    result.push("[agents]");
    for (const [key, value] of pending) {
      result.push(`${key} = ${JSON.stringify(value)}`);
    }
  }

  return result.join("\n").trimEnd();
}

export function listZcAgentConfigNames(content: string): readonly string[] {
  return content
    .split(/\r?\n/)
    .map((line) => line.trim().match(zcAgentSectionPattern)?.[1] ?? null)
    .filter((name): name is string => name !== null);
}

export function stripManagedZcAgentSections(
  content: string,
  managedAgentNames?: readonly string[],
  managedDefaults: readonly ManagedCodexAgentDefault[] = [],
): string {
  const lines = content.split(/\r?\n/);
  const kept: string[] = [];
  const managedNames = managedAgentNames === undefined
    ? null
    : new Set(managedAgentNames);
  let skipping = false;
  let inAgentsSection = false;
  const ownedDefaults = new Map(managedDefaults.map((entry) => [entry.key, entry.value]));

  for (const line of lines) {
    const trimmed = line.trim();

    if (zcGeneratedCommentLines.has(trimmed)) {
      continue;
    }

    if (isCodexAgentsSection(line)) {
      inAgentsSection = true;
      skipping = false;
      kept.push(line);
      continue;
    }
    if (inAgentsSection && isTomlSection(line)) {
      inAgentsSection = false;
    }
    if (inAgentsSection) {
      const defaultMatch = line.match(codexAgentDefaultPattern);
      if (
        defaultMatch
        && ownedDefaults.get(defaultMatch[2] as CodexAgentDefaultKey) === defaultMatch[4]
      ) {
        continue;
      }
    }

    const agentSection = trimmed.match(zcAgentSectionPattern);
    if (
      agentSection
      && (managedNames === null || managedNames.has(agentSection[1]!))
    ) {
      skipping = true;
      continue;
    }

    if (skipping && tomlSectionPattern.test(trimmed)) {
      skipping = false;
    }

    if (!skipping) {
      kept.push(line);
    }
  }

  return kept.join("\n").trimEnd();
}

export function isCodexAgentConfigContent(content: string): boolean {
  return content.split(/\r?\n/).some((line) => zcAgentSectionPattern.test(line.trim()));
}

export function mergeOwnedCodexAgentConfigWithDefaults(
  existingContent: string | undefined,
  generatedContent: string,
  previouslyManagedAgentNames: readonly string[],
  previouslyManagedDefaults: readonly ManagedCodexAgentDefault[],
): CodexAgentConfigMergeResult {
  if (
    inlineAgentsPattern.test(existingContent ?? "")
    || dottedAgentDefaultPattern.test(existingContent ?? "")
    || agentsArrayTablePattern.test(existingContent ?? "")
    || quotedAgentsSectionPattern.test(existingContent ?? "")
    || quotedAgentDefaultKeyPattern.test(existingContent ?? "")
  ) {
    throw new Error("无法安全合并 inline 或 quoted [agents] 默认配置；请先将其转换为标准 [agents] 表和裸键。");
  }
  const generatedDefaults = readCodexAgentDefaults(generatedContent);
  const existingDefaults = readCodexAgentDefaults(existingContent ?? "");
  const previouslyOwned = new Map(previouslyManagedDefaults.map((entry) => [entry.key, entry.value]));
  const defaultsToWrite = new Map<CodexAgentDefaultKey, string>();
  const managedDefaults: ManagedCodexAgentDefault[] = [];

  for (const key of codexAgentDefaultKeys) {
    const generatedValue = generatedDefaults.get(key);
    if (generatedValue === undefined) {
      continue;
    }
    const existingValue = existingDefaults.get(key);
    if (existingValue === undefined || existingValue === previouslyOwned.get(key)) {
      defaultsToWrite.set(key, generatedValue);
      managedDefaults.push({ key, value: generatedValue });
    }
  }

  const generatedBlock = stripGeneratedCodexAgentDefaults(generatedContent);
  const baseContent = stripManagedZcAgentSections(
    existingContent ?? "",
    [...previouslyManagedAgentNames, ...listZcAgentConfigNames(generatedContent)],
  );
  const contentWithDefaults = mergeCodexAgentDefaults(baseContent, defaultsToWrite);
  const content = generatedBlock
    ? contentWithDefaults.trim()
      ? `${contentWithDefaults}\n\n${generatedBlock}\n`
      : `${generatedBlock}\n`
    : contentWithDefaults.trim()
      ? `${contentWithDefaults}\n`
      : "";

  return { content, managedDefaults };
}

export function mergeCodexAgentConfig(existingContent: string | undefined, generatedContent: string): string {
  return mergeOwnedCodexAgentConfigWithDefaults(existingContent, generatedContent, [], []).content;
}

export function mergeOwnedCodexAgentConfig(
  existingContent: string | undefined,
  generatedContent: string,
  previouslyManagedAgentNames: readonly string[],
  previouslyManagedDefaults: readonly ManagedCodexAgentDefault[] = [],
): string {
  return mergeOwnedCodexAgentConfigWithDefaults(
    existingContent,
    generatedContent,
    previouslyManagedAgentNames,
    previouslyManagedDefaults,
  ).content;
}
